# Generated by Django 5.2.6 on 2025-09-14 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpos', models.PositiveIntegerField(db_index=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('s3_path', models.CharField(db_index=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyphotos', to='timelines.timeline')),
            ],
            options={
                'verbose_name': 'KeyPhoto',
                'verbose_name_plural': 'KeyPhotos',
                'db_table': 'keyphoto',
                'ordering': ['timeline', 'tpos'],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpos', models.PositiveIntegerField(db_index=True)),
                ('s3_path', models.CharField(db_index=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_keyphoto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_transition', to='visuals.keyphoto')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='timelines.timeline')),
                ('to_keyphoto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_transition', to='visuals.keyphoto')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
                'db_table': 'transition',
                'ordering': ['timeline', 'tpos'],
            },
        ),
        migrations.AddConstraint(
            model_name='keyphoto',
            constraint=models.UniqueConstraint(fields=('timeline', 'tpos'), name='unique_keyphoto_timeline_pos'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('timeline', 'tpos'), name='unique_transition_timeline_pos'),
        ),
    ]
