# Generated by Django 5.2.6 on 2025-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyphoto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
