# Generated by Django 5.2.6 on 2025-09-18 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timeline',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_timeline_user_name'),
        ),
    ]
